site_name: Athena Docs
repo_url: https://github.com/Marcus-Holanda777/athena-mvsh
repo_name: mvsh777/athena-mvsh
edit_uri: tree/main/docs

theme:
  name: "material"
  language: pt-BR
  palette:

    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - mkdocstrings
  - search

nav:
  - Athena Docs: index.md
  - referencia.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Marcus-Holanda777/athena-mvsh
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/athena-mvsh/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcus-holanda-b544a81b5/