name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tests:
    name: Testar e formatar o projeto
    runs-on: ubuntu-latest
    steps:
      - name: Copiar repositorio
        uses: actions/checkout@v4
    
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
            python-version: 3.11.x

      - name: Instalar o Poetry
        run: pip install poetry
      
      - name: Instalar as dependencias
        run: poetry install --without dev
     
      - name: Executar ruff check
        run: poetry run ruff check .
      
      - name: Executar ruff format
        run: poetry run ruff format .
      
      - name: Executar tests
        run: poetry run pytest
  
  docs:
    name: Gerar a documentacao
    runs-on: ubuntu-latest
    steps:
      - name: Copiar repositorio
        uses: actions/checkout@v4
      
      - name: Configurar o credenciais
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
            python-version: 3.11.x

      - name: Instalar o Poetry
        run: pip install poetry
      
      - name: Instalar as dependencias
        run: poetry install --without docs
      
      - name: Gerar a documentacao
        run: poetry run mkdocs build --clean
      
      - name: Deploy da documentacao
        run: poetry run mkdocs gh-deploy --force --clean

  publish:
    name: Publicar projeto no PYPI
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [tests, docs]
    steps:
      - name: Copiar repositorio
        uses: actions/checkout@v4
    
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
            python-version: 3.11.x

      - name: Instalar o Poetry
        run: pip install poetry
    
      - name: Configura o Poetry
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
     
      - name: Build and Publish
        run: |
          poetry build
          poetry publish